spring.application.name=snapfood 

#Data Source :
spring.datasource.url=jdbc:mysql://localhost:3306/SpringBoot
spring.datasource.username=root
spring.datasource.password=Rupesh6299

#jpa and hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update

#1. none = hibernate will not manage
#2. validate = hibernate will validate the schema against your entities but will not make any changes
#3. update = hibernate will modify the schema to match the entity definitions but will not drop  any existing data and table
#4. create-drop = similar to create, but the schema is drop automatically when the application is shutdown
